spring.datasource.url=jdbc:mysql://localhost:3306/appverse_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.application.name=appverse-ai
logging.file.name=logs/appverse.log
logging.level.com.wipro=DEBUG
app.jwt.secret=AppVerseSecretKey2024MustBe32CharsLong!
app.jwt.expiration=36000000
